server:
  port: 5000
spring:
  datasource:
    platform: postgres
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    #hibernate:
    #  ddl-auto: create-drop

    generate-ddl: true
  h2:
    console.enabled: true
