server:
  port: 5000
spring:
  datasource:
    platform: postgres
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    #hibernate:
    #  ddl-auto: create-drop

    generate-ddl: true
  h2:
    console.enabled: true
  jacoco:
    agent:
      it:
        arg:
          - destfile=target/jacoco-it.exec
          - append=true
  mail:
    host: ${MAIL_HOST}
    password: ${MAIL_PASSWORD}
    port: 465
    properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
    username: ${MAIL_USERNAME}

jwt:
  secret: ThisIsTheJWTSECRETSECRE78