server:
  port: 8080
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://carrrier-pigeon-db.c92ukfffldkd.us-west-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: JanHu3!!!
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    #hibernate:
    #  ddl-auto: create-drop

    generate-ddl: true
  h2:
    console.enabled: true
